sudo: false
dist: trusty
language: cpp

os:
  - linux

cache:
  directories:
    - $HOME/cache
    - $HOME/.ccache
    - $HOME/Library/Caches/Homebrew

stages:
  - prepare linux
  - test # Default stage with matrix
  - osx
  - deploy

addons:
  apt:
    sources:
      - sourceline: 'ppa:nschloe/eigen-backports'
      - sourceline: 'deb http://www.icub.org/ubuntu trusty contrib/science'
    packages:
      - cmake3
      - ninja-build
      # YARP / iCub / wb-toolbox
      - icub-common
      - libqt5opengl5-dev
      - libeigen3-dev

compiler:
  - gcc
  - clang

env:
  global:
    - TRAVIS_CMAKE_GENERATOR="Ninja"
    - DEPS_BRANCH="master"
  matrix:
    - TRAVIS_BUILD_TYPE="Release"
    - TRAVIS_BUILD_TYPE="Debug"

# ==============
# STAGE: prepare
# ==============

stage_prepare:
  script: &prepare_script
    # Clean the dependencies cache from previous builds (ccache is instead kept)
    - rm -rf $DEPS_CACHE
    - mkdir -p $DEPS_CACHE

    # Select the branch for the dependencies. The default is master.
    - if [[ "$TRAVIS_PULL_REQUEST" = "true" && "$TRAVIS_BRANCH" != "master" ]] ; then export DEPS_BRANCH="devel" ; fi
    - if echo $TRAVIS_COMMIT_MESSAGE | grep -F -q "[ci devel]" ; then export DEPS_BRANCH="devel" ; fi
    - if echo $TRAVIS_COMMIT_MESSAGE | grep -F -q "[devel ci]" ; then export DEPS_BRANCH="devel" ; fi
    - echo "Using $DEPS_BRANCH for dependencies"

    # Install dependencies
    # --------------------

    # Limit concurrency for some project in order to avoid let the CI fail
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then CMAKE_BUILD_OPTIONS="-- -j4" ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]   ; then CMAKE_BUILD_OPTIONS="" ; fi

    - mkdir $HOME/git
    - export CXXFLAGS="-Wno-unused-command-line-argument"

    # Install YCM
    - cd $HOME/git
    - git clone --depth 1 https://github.com/robotology/ycm.git
    - cd ycm
    - git checkout ${DEPS_BRANCH}
    - mkdir build && cd build
    - >-
      cmake .. \
        -G"$TRAVIS_CMAKE_GENERATOR" \
        -DCMAKE_INSTALL_PREFIX=$DEPS_CACHE
    - cmake --build . --target install

    # Install Yarp
    - cd $HOME/git
    - git clone --depth 1 https://github.com/robotology/yarp.git
    - cd yarp
    - mkdir build && cd build
    - >-
      cmake .. \
        -G"$TRAVIS_CMAKE_GENERATOR" \
        -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE \
        -DCMAKE_INSTALL_PREFIX=$DEPS_CACHE \
        -DCREATE_LIB_MATH=ON
    - cmake --build . --config $TRAVIS_BUILD_TYPE --target install

    # Install icub-main
    - cd $HOME/git
    - git clone --depth 1 https://github.com/robotology/icub-main.git
    - cd icub-main
    - mkdir build && cd build
    - >-
      cmake .. \
        -G"$TRAVIS_CMAKE_GENERATOR" \
        -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE \
        -DCMAKE_INSTALL_PREFIX=$DEPS_CACHE
    - cmake --build . --config $TRAVIS_BUILD_TYPE --target install $CMAKE_BUILD_OPTIONS

    # Install iDynTree
    - cd $HOME/git
    - git clone --depth 1 https://github.com/robotology/idyntree.git
    - cd idyntree
    - mkdir build && cd build
    - >-
      cmake .. \
        -G"$TRAVIS_CMAKE_GENERATOR" \
        -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE \
        -DCMAKE_INSTALL_PREFIX=$DEPS_CACHE
    - cmake --build . --config $TRAVIS_BUILD_TYPE --target install $CMAKE_BUILD_OPTIONS

# ===================
# STAGE: test (linux)
# ===================

before_install: &before_install
  # Prepare ccache
  - mkdir -p $HOME/.local/bin
  - ln -s $(which ccache) $HOME/.local/bin/$CC
  - ln -s $(which ccache) $HOME/.local/bin/$CXX
  - export PATH=/$HOME/.local/bin:$PATH
  - echo "max_size = 1.0G" > $HOME/.ccache/ccache.conf
  # Setup the dependencies cache
  - export DEPS_CACHE=$HOME/cache/$TRAVIS_OS_NAME/$TRAVIS_BUILD_TYPE
  - export PATH=$PATH:$DEPS_CACHE/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DEPS_CACHE/lib
  - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEPS_CACHE

script: &script
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake -G"$TRAVIS_CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE ..
  - cmake --build . --config $TRAVIS_BUILD_TYPE

# ==========
# STAGE: osx
# ==========

stage_osx:
  before_install: &osx_before_install
    # Setup the dependencies cache
    - export DEPS_CACHE=$HOME/cache/$TRAVIS_OS_NAME/$TRAVIS_BUILD_TYPE
    - export PATH=$PATH:$DEPS_CACHE/bin
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DEPS_CACHE/lib
    - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEPS_CACHE
  install: &osx_install
    # Setup ccache
    - brew install ccache
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    # Install dependencies
    - brew install eigen ace tinyxml gsl

# =============
# STAGE: deploy
# =============

stage_deploy:
  install: &deploy_install
    - pip3 install --user Pygments mkdocs mkdocs-material
    - export PATH=$HOME/.local/bin:$PATH
  script: &deploy_script
    # Setup the dependencies cache
    - export DEPS_CACHE=$HOME/cache/$TRAVIS_OS_NAME/$TRAVIS_BUILD_TYPE
    - export PATH=$PATH:$DEPS_CACHE/bin
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DEPS_CACHE/lib
    - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEPS_CACHE
    # Clone the gh-pages branch
    - GH_PAGES_ROOTDIR=$HOME/gh-pages
    - export GH_REPO_ORG=${TRAVIS_REPO_SLUG%*/*}
    - export GH_REPO_NAME=${TRAVIS_REPO_SLUG#*/*}
    - export GH_REPO_REF="github.com/$GH_REPO_ORG/$GH_REPO_NAME.git"
    # Select the deploy folder
    - if [ "$TRAVIS_BRANCH" = "master" ] ; then DEPLOY_FOLDER=$GH_PAGES_ROOTDIR ; fi
    - if [ "$TRAVIS_BRANCH" = "devel" ] ; then DEPLOY_FOLDER=$GH_PAGES_ROOTDIR/devel ; fi
    # Check if the gh-pages branch exists and clone it
    - cd $TRAVIS_BUILD_DIR
    - git ls-remote --heads --exit-code https://$GH_REPO_REF gh-pages || travis_terminate 1
    - git clone -b gh-pages https://$GH_REPO_REF $GH_PAGES_ROOTDIR
    # Push only the current branch
    - cd $GH_PAGES_ROOTDIR
    - git config push.default simple
    # Disable GitHub jekyll generation
    - touch $GH_PAGES_ROOTDIR/.nojekyll
    # Generate documentation
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DWBTOOLBOX_BUILD_DOCS:BOOL=TRUE
    - make dox || travis_terminate 1
    - make mkdocs || travis_terminate 1
    # Move the new doxygen documentation to the deploy folder
    - rm -rf $DEPLOY_FOLDER/doxygen
    - mv $DOXYGEN_INPUT_FOLDER/html $DEPLOY_FOLDER/doxygen
    # Move the new mkdocs documentation to the deploy folder
    - rm -rf $DEPLOY_FOLDER/mkdocs
    - mv $MKDOCS_INPUT_FOLDER $DEPLOY_FOLDER/mkdocs
    # Deploy the folder
    - cd $GH_PAGES_ROOTDIR
    - git remote add origin-botlogin https://$GIT_COMMITTER_USERNAME:$DEPLOY_TOKEN@$GH_REPO_REF
    - git add --all
    - COMMIT_AUTHOR="$(git --no-pager show -s --format='%an <%ae>' $TRAVIS_COMMIT)"
    - >-
      git commit -m "Automatic docs deployment Travis#${TRAVIS_BUILD_NUMBER}" \
                 -m "Commit: https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT" \
                 --author "$COMMIT_AUTHOR"
    - git push --force origin-botlogin gh-pages

# ======================
# BUILD JOBS FROM STAGES
# ======================

jobs:
  include:
    - &prepare_template
      stage: prepare linux
      before_install: *before_install
      install: skip
      script: *prepare_script
      compiler: clang
      env:
        TRAVIS_BUILD_TYPE="Release"
    - <<: *prepare_template
      compiler: gcc
    - <<: *prepare_template
      compiler: clang
      env:
        TRAVIS_BUILD_TYPE="Debug"
    - <<: *prepare_template
      compiler: gcc
      env:
        TRAVIS_BUILD_TYPE="Debug"
    - &osx_template
      stage: osx
      os: osx
      compiler: clang
      osx_image: xcode9.3
      before_install: *osx_before_install
      install: *osx_install
      before_script: *prepare_script
      script: *script
      env:
        TRAVIS_CMAKE_GENERATOR="Xcode"
        TRAVIS_BUILD_TYPE="Debug"
    - <<: *osx_template
      env:
        TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
        TRAVIS_BUILD_TYPE="Debug"
    - &deploy_template
      stage: deploy
      compiler:
      cache:
      if: ((branch = master) AND (type != pull_request))
      before_install: skip
      install: *deploy_install
      before_script: skip
      script: *deploy_script
      after_success: skip
      env:
        GIT_COMMITTER_USERNAME=LOC2Bot
        GIT_COMMITTER_NAME=LOC2Bot
        GIT_COMMITTER_EMAIL=locomotion.control@gmail.com
        DOXYGEN_INPUT_FOLDER=$TRAVIS_BUILD_DIR/build/doc/doxygen
        MKDOCS_INPUT_FOLDER=$TRAVIS_BUILD_DIR/build/doc/mkdocs
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-gui
            - graphviz
            - python3-pip
    - <<: *deploy_template
      if: ((branch = devel) AND (type != pull_request))

# notifications:
#  email:
#    - whowantstobemantainedr@email.com
