# Project information
site_name: 'WBT'
site_url: https://robotology.github.io/wb-toolbox/
site_description: 'A Simulink Toolbox for Whole-Body Control'
site_author: 'Diego Ferigo'

# Repository
repo_name: robotology/wb-toolbox
repo_url: 'https://github.com/robotology/wb-toolbox'
edit_uri: 'edit/master/doc/mkdocs/data'

# Configuration
docs_dir: 'data'
theme:
    name: 'material'
    palette:
        primary: blue grey
        accent: amber
    feature:
        tabs: true
    # favicon:
    #     icon: dashboard
    icon:
        logo: fontawesome/solid/cube

# Copyright
copyright: 'Copyright &copy; 2020 Istituto Italiano di Tecnologia'

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.magiclink:
        user: robotology
        repo: wb-toolbox
        repo_url_shortener: true
        repo_url_shorthand: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - markdown.extensions.toc:
        permalink: true

# Page tree
nav:
    - Home: 'index.md'
    - Install: 'install.md'
    - Troubleshooting: 'troubleshooting.md'
    - Documentation [master]: https://robotology.github.io/wb-toolbox/doxygen/
    - Documentation [devel]: https://robotology.github.io/wb-toolbox/devel/doxygen/
    - Tutorials:
        - Introduction: tutorial_introduction.md
        - Basic Simulink simulation: simulink_basic.md
        - Use model blocks: simulink_model_blocks.md
        - Simulink and Gazebo: simulink_gazebo.md
    - Migration:
        - From WBI-Toolbox: 'Migration_from_WBI-Toolbox_1.0.md'
        - From WB-Toolbox 2.0: 'Migration_from_WB-Toolbox_2.0.md'
    - About: 'about.md'
    - License: 'license.md'
